### ISSUE TITLE
Followed instruction to install djangocms-form-builder got error message NoReverseMatch: 'form_builder' is not a registered namespace 

### ISSUE THREAD

**Issue by rolandf** [fsbraun/djangocms-form-builder#7]
Hello,
I just added djangocms-form-builder at the end of installed apps in the settings.py file for django-cms-quickstart for v4.1x that was running fine locally outside of docker on my ubuntu dev pc.

Exception when rendering template in FormPlugin (id=15)
NoReverseMatch: 'form_builder' is not a registered namespace 

Not sure what to do.

**Comment by rolandf** [comment]
The error was between my chair and my keyboard. Forgot to call collectstatic before running project.

**Comment by fsbraun** [comment]
Probably a missing server restart, though.
